version: "3.3"
# Указываем раздел со связанными сервисами

services:
  nginx:
    container_name: nuxt_nginx
    depends_on:
      - nuxt
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      # Используем свой nginx конфиг, он заменит дефолтный в контейнере
      - ./docker/nginx:/etc/nginx/conf.d
      # Монтируем папку с логами на хост машину для более удобного доступа
      - ./docker/logs:/var/log/nginx/
    restart: always

  nuxt:
    build:
      context: .
    image: nuxt_dev
    container_name: nuxt_app
    command: npm run dev
    volumes:
    - .:/app
    - /app/node_modules
    ports:
      - "3000:3000"
    restart: always

  postgres:
    container_name: nuxt_pgsql
    image: postgres:latest
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - habrdb-data:/var/lib/postgresql/data

volumes:
  habrdb-data: